# Generated by Django 3.0.7 on 2020-06-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_code', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=10)),
                ('age_group', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('date_specimen', models.CharField(max_length=50)),
                ('date_result_release', models.CharField(max_length=50)),
                ('date_died', models.CharField(max_length=50)),
                ('date_recovered', models.CharField(max_length=50)),
                ('removal_type', models.CharField(max_length=30)),
                ('date_rem_rep', models.CharField(max_length=50)),
                ('is_admitted', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=70)),
                ('province', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('city_psgc', models.CharField(max_length=70)),
                ('health_status', models.CharField(max_length=70)),
                ('is_quarantined', models.CharField(max_length=70)),
                ('date_onset', models.CharField(max_length=50)),
                ('is_pregnant', models.CharField(max_length=5)),
                ('validation', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['date_result_release'],
            },
        ),
        migrations.CreateModel(
            name='WorldwideCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('case_per_day', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
