# Generated by Django 3.0.7 on 2020-06-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='date_rep_conf',
            field=models.CharField(default='', max_length=50),
        ),
    ]
